### ISSUE TITLE
LAS directory organisation

### ISSUE THREAD

**Issue by ScottWales** [coecms/climate-cms#15]
Currently all files are in one unreadable list, can some structure be added?

**Comment by aidanheerdegen** [comment]
"Docs are at http://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/adding-gridded-data, looks like you can add custom categories for data"

**Comment by ScottWales** [comment]
To use the thredds layout in LAS you need to add the `--category` flag to addXml.sh, e.g.

```
sudo -u tomcat JAVA_HOME="/usr/lib/jvm/jre" /usr/local/las/las.v8.2/bin/addXML.sh --verbose -t http://localhost:8080/thredds/catalog.xml --category
```

**Comment by ScottWales** [comment]
This is working, but needs to be added to #14
